import { config } from './config.js';

export const HELM = {
  greeting: "I'm Helm. AgentHelm gives you a personal AI agent that lives in Telegram and actually does things — think of it as hiring an intern who never sleeps and never asks for equity.\n\nBefore we get started, here's what you'll need:\n• A Google account to connect (so your agent can handle email)\n• A MiniMax API key from platform.minimax.io — or an Anthropic key if you're feeling bougie\n• A Telegram bot token from @BotFather\n\nWhat would you use a personal AI agent for?",
  askGmail: "Love it. One more thing before I pass you along — what's your Gmail address? We'll use it to connect your agent to your inbox.",
  pendingApproval: "Great answer! If it were up to me, I'd hand you the keys right now. But my boss reviews every application personally — he's the paranoid type. Thinks everyone is a bot. Ironic, I know. Sit tight, I'll ping you when you're cleared.",
  waitingOnClearance: "Waiting on clearance. You'll hear from me.",
  approved: "Clearance granted. Let's get you set up.",
  rejected: "Not the right fit for this round. We'll keep your info on file.",
  gmailOauth: "First, connect your Gmail. This is what your agent will use to read and send email on your behalf.",
  gmailConnected: "Gmail connected.",
  gmailFailed: "Gmail connection failed. Try again.",
  minimaxInstructions: "Head to platform.minimax.io — create an account and grab your API key. Paste it here when you have it.",
  minimaxInvalid: "That key didn't check out. Try again.",
  botfatherInstructions: "Open @BotFather on Telegram. Send /newbot, give your agent a name, and paste the token it gives you back here.",
  botfatherInvalid: "That token didn't check out. Make sure you copied the full thing.",
  notifyBotInstructions: `One more thing — message @${config.notifyBotUsername} on Telegram. That's how I'll reach you when something needs your attention: re-authentication, key renewals, status updates. One message is all it takes.`,
  notifyBotTimeout: `I didn't see you message @${config.notifyBotUsername}. You can do that later — continuing setup.`,
  provisioning: "Your agent is spinning up. Stand by.",
  validating: "Deploying your agent. This takes a moment.",
  validatingTimeout: "Taking longer than expected. I'll follow up shortly.",
  passwordSetup: "Your agent is live. Set up your AgentHelm account — this link expires in 24 hours.",
  done: `You're all set. Your agent is live.\n\nSign in to your dashboard at ${config.dashboardUrl} — use the same Google account you connected. That's where you'll manage permissions, review approvals, and check on your agent.\n\nJoin the Agent Helm Support Group for help, updates, and tips from other users: https://t.me/+5NUos0uOs4JjYWUx`,
  error: "Something went wrong on my end. I've flagged it. Sit tight.",
  alreadyDone: "You're already set up. Your agent is live.",
};
